version: 2

sources:
  - name: raw
    schema: analytics_raw
    tables:
      - name: raw_erp_invoices
        loaded_at_field: loaded_at
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
      - name: raw_credit_notes
        loaded_at_field: loaded_at
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
      - name: raw_fx_rates
        loaded_at_field: loaded_at
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
      - name: raw_gl_ledger
        loaded_at_field: loaded_at
        freshness:
          warn_after: {count: 30, period: day}
          error_after: {count: 60, period: day}
