rev_recon:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_POSTGRES_HOST', 'localhost') }}"
      port: 5432
      user: "{{ env_var('DBT_POSTGRES_USER', 'postgres') }}"
      pass: "{{ env_var('DBT_POSTGRES_PASSWORD', 'postgres') }}"
      dbname: "{{ env_var('DBT_POSTGRES_DB', 'analytics') }}"
      schema: "{{ env_var('DBT_POSTGRES_SCHEMA', 'analytics') }}"
      threads: 4
